/* tslint:disable */
/* eslint-disable */
/**
 * SweetPotato Server 2 API
 * Advanced Sonolus API server with adds minimum features (TypeScript)   Development repository is [here](https://github.com/PurplePalette/sonolus-uploader-core2)  ### Sonolus-Version - 0.5.9  ### Features - supports uploading level - tests server for chart testing - simple upload endpoint  ### Original comments - Sonolusの基本APIを拡張する感じのAPI(Sonolus-Express) - ユーザー認証はFirebaseAuthorizationを通してやる。 - データベースはファイル構造そのまま
 *
 * The version of the OpenAPI document: 0.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from "./configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';

export const BASE_PATH = "http://localhost:5000".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}
