/* tslint:disable */
/* eslint-disable */
/**
 * SweetPotato Server 2 API
 * Advanced Sonolus API server with adds minimum features (TypeScript)   Development repository is [here](https://github.com/PurplePalette/sonolus-uploader-core2)  ### Sonolus-Version - 0.5.9  ### Features - supports uploading level - tests server for chart testing - simple upload endpoint  ### Original comments - Sonolusの基本APIを拡張する感じのAPI(Sonolus-Express) - ユーザー認証はFirebaseAuthorizationを通してやる。 - データベースはファイル構造そのまま
 *
 * The version of the OpenAPI document: 0.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

